#ifndef SENSING_AND_CONTROL_UNIT_SRC_ERROR_HPP
#define SENSING_AND_CONTROL_UNIT_SRC_ERROR_HPP
enum ErrorLevel
{
    INFO,
    WARNING,
    ERROR,
    FATAL
};
typedef enum ErrorLevel ErrorLevel;
#endif // SENSING_AND_CONTROL_UNIT_SRC_ERROR_HPP