#ifndef SENSIING_AND_CONTROL_UNIT_SRC_THRUSTER_THRUSTER_INFO_HPP
#define SENSIING_AND_CONTROL_UNIT_SRC_THRUSTER_THRUSTER_INFO_HPP
const int kThrusterCount = 7;
const int32_t kInitThrusterPwm = 1474;
const int32_t kMinPwmValue = 1100;
const int32_t kMaxPwmValue = 1900;
#endif // SENSIING_AND_CONTROL_UNIT_SRC_THRUSTER_THRUSTER_INFO_HPP
