#ifndef SENSING_AND_CONTROL_UNIT_SRC_THRUSTER_THRUSTER_INFO_HPP
#define SENSING_AND_CONTROL_UNIT_SRC_THRUSTER_THRUSTER_INFO_HPP
const int kThrusterCount = 6;
const int kThrusterNeutralPWM = 1500;
const int kThrusterPins[]={2,3,4,5,6,7};
#endif // SENSIING_AND_CONTROL_UNIT_SRC_THRUSTER_THRUSTER_INFO_HPP
